"base_path" : "."
"base_url" : "https://api.crowdin.com"
"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"preserve_hierarchy": false

files: [
 {
  "source" : "crowdin-work/%repository.name%.ini",
  "translation" : "data/locale/%locale%.ini",
  "skip_untranslated_strings" : true
 }
]
